;;; This code was generated by a script

        SECTION code_compiler
        GLOBAL  _zxn_p3cont_af
        GLOBAL  _zxn_p3cont_af_err
	GLOBAL  zxn_p3cont_errcheck

;;; On entry, stack holds
;;;     retaddr, af, bc, de, hl, ix, zxn_p3call_adjstack

_zxn_p3cont_af_err:
        call	zxn_p3cont_errcheck	; either won't return or pops adjstack
_zxn_p3cont_af:
	pop	hl		; pop value for ix (ignored)
	pop	hl		; pop value for hl (ignored)
	pop	hl		; pop value for de (ignored)
	pop	hl		; pop value for bc (ignored)
	pop	hl		; pop value for af (to return)
	ret			; done
