;;; This code was generated by a script

	SECTION code_compiler
	GLOBAL  _zxn_p3cont_ix
	GLOBAL  _zxn_p3cont_ix_err
	GLOBAL  zxn_p3cont_errcheck

;;; On entry, stack holds
;;;     retaddr, af, bc, de, hl, ix, zxn_p3call_adjstack

_zxn_p3cont_ix_err:
	call	zxn_p3cont_errcheck	; might not return
_zxn_p3cont_ix:
	pop     af		; throw away zxn_p3call_adjstack, not needed
				; (only used if user writes a custom handler)
	pop	hl		; pop value for ix (to return)
	pop	af		; pop value for hl (ignored)
	pop	af		; pop value for de (ignored)
	pop	af		; pop value for bc (ignored)
	pop	af		; pop value for af (ignored)
	ret			; done
